python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for sowing --s1_bands [0] --use_testing True;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for sowing --s1_bands [1] --use_testing True;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for sowing --s1_bands [0,1] --use_testing True;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for sowing --s1_bands [0,1,2] --use_testing True;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for sowing --s1_bands [1,2] --use_testing True;

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for harvesting --s1_bands [0] --use_testing True;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for harvesting --s1_bands [1] --use_testing True;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for harvesting --s1_bands [0,1] --use_testing True;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for harvesting --s1_bands [0,1,2] --use_testing True;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for harvesting --s1_bands [1,2] --use_testing True;

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for transplanting --s1_bands [0] --use_testing True;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for transplanting --s1_bands [1] --use_testing True;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for transplanting --s1_bands [0,1] --use_testing True;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for transplanting --s1_bands [0,1,2] --use_testing True;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for transplanting --s1_bands [1,2] --use_testing True;


