python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for sowing --use_testing True --run_name 'S1-Sow(All)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for transplanting --use_testing True --run_name 'S1-Harvest(All)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for harvesting --use_testing True --run_name 'S1-Trans(All)';

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for sowing --s1_bands [0] --use_testing True --run_name 'S1-Sow(VV)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for transplanting --s1_bands [0] --use_testing True --run_name 'S1-Harvest(VV)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for harvesting --s1_bands [0] --use_testing True --run_name 'S1-Trans(VV)';

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for sowing --s1_bands [1] --use_testing True --run_name 'S1-Sow(VH)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for transplanting --s1_bands [1] --use_testing True --run_name 'S1-Harvest(VH)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for harvesting --s1_bands [1] --use_testing True --run_name 'S1-Trans(VH)';

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for sowing --s1_bands [0,1] --use_testing True --run_name 'S1-Sow(VV,VH)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for transplanting --s1_bands [0,1] --use_testing True --run_name 'S1-Harvest(VV,VH)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for harvesting --s1_bands [0,1] --use_testing True --run_name 'S1-Trans(VV,VH)';

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for sowing --s1_bands [0,2] --use_testing True --run_name 'S1-Sow(VV,Angle)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for transplanting --s1_bands [0,2] --use_testing True --run_name 'S1-Harvest(VV,Angle)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for harvesting --s1_bands [0,2] --use_testing True --run_name 'S1-Trans(VV,Angle)';

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for sowing --s1_bands [1,2] --use_testing True --run_name 'S1-Sow(VH,Angle)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for transplanting --s1_bands [1,2] --use_testing True --run_name 'S1-Harvest(VH,Angle)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --date_pred_for harvesting --s1_bands [1,2] --use_testing True --run_name 'S1-Trans(VH,Angle)';
