python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 1 --date_pred_for sowing --use_testing True --run_name 'S2-Sow(All)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 1 --date_pred_for harvesting --use_testing True --run_name 'S2-Harvest(All)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 1 --date_pred_for transplanting --use_testing True --run_name 'S2-Trans(All)';

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --date_pred_for sowing --s2_bands [3] --use_testing True --run_name 'S2-Sow(RE1)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --date_pred_for harvesting --s2_bands [3] --use_testing True --run_name 'S2-Harvest(RE1)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --date_pred_for transplanting --s2_bands [3] --use_testing True --run_name 'S2-Trans(RE1)';

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --date_pred_for sowing --s2_bands [4] --use_testing True --run_name 'S2-Sow(RE2)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --date_pred_for harvesting --s2_bands [4] --use_testing True --run_name 'S2-Harvest(RE2)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --date_pred_for transplanting --s2_bands [4] --use_testing True --run_name 'S2-Trans(RE2)';

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --date_pred_for sowing --s2_bands [5] --use_testing True --run_name 'S2-Sow(RE3)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --date_pred_for harvesting --s2_bands [5] --use_testing True --run_name 'S2-Harvest(RE3)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --date_pred_for transplanting --s2_bands [5] --use_testing True --run_name 'S2-Trans(RE3)';

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --date_pred_for sowing --s2_bands [7] --use_testing True --run_name 'S2-Sow(RE4)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --date_pred_for harvesting --s2_bands [7] --use_testing True --run_name 'S2-Harvest(RE4)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --date_pred_for transplanting --s2_bands [7] --use_testing True --run_name 'S2-Trans(RE4)';

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --date_pred_for sowing --s2_bands [3,4,5,7] --use_testing True --run_name 'S2-Sow(RE1-4)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --date_pred_for harvesting --s2_bands [3,4,5,7] --use_testing True --run_name 'S2-Harvest(RE1-4)';
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --date_pred_for transplanting --s2_bands [3,4,5,7] --use_testing True --run_name 'S2-Trans(RE1-4)';
