#python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,0] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
#python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,0,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
#python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,0,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
#python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,1] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
#python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,1] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
#python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,1] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
#python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,1] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
#python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,1,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
#python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,1,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
#python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,1,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
#python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,1,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,1,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,1,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,1,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,1,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [2,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [2,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [2,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [2,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,4] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,1,2,3,4,5,6,7] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,1,2,3,4,5,6,7] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,1,2,3,4,5,6,7] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,1,2,3,4,5,6,7] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,1,2,3,4,5,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,1,2,3,4,5,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,1,2,3,4,5,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,1,2,3,4,5,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [7] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [7] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [7] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [7] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,7] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,7] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,7] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,7] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;

#S2
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,0,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,0,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,0,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,0,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [1,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [1,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [1,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [1,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,6] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [0,1,2,3,4,5,6,7,8,9] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [0,1,2,3,4,5,6,7,8,9] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [0,1,2,3,4,5,6,7,8,9] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [0,1,2,3,4,5,6,7,8,9] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [3] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [3] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [3] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [3] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [4] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [4] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [4] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [4] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [5] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [5] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [5] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [5] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [7] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [7] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [7] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [7] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [3,4,5,7] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [3,4,5,7] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [3,4,5,7] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [3,4,5,7] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;


python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0,1,2] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0,1,2] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0,1,2] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0,1,2] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [2] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [2] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [2] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [2] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [1] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [1] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [1] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [1] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0,2] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0,2] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0,2] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0,2] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;

python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [1,2] --date_pred_for sowing --use_testing True --resize_planet True --seed 0;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [1,2] --date_pred_for sowing --use_testing True --resize_planet True --seed 1;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [1,2] --date_pred_for sowing --use_testing True --resize_planet True --seed 2;
python train_date_prediction.py --path_to_cauvery ../../Documents/ --model_name unet-fc --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [1,2] --date_pred_for sowing --use_testing True --resize_planet True --seed 3;

