python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,1]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,1]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,1]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,1]  --use_testing True --resize_planet False --seed 3;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,1,4]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,1,4]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,1,4]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,1,4]  --use_testing True --resize_planet False --seed 3;

python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,4]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,4]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,4]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,4]  --use_testing True --resize_planet False --seed 3;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,1,4]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,1,4]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,1,4]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,1,4]  --use_testing True --resize_planet False --seed 3;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [2,4]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [2,4]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [2,4]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [2,4]  --use_testing True --resize_planet False --seed 3;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,4]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,4]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,4]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [3,2,4]  --use_testing True --resize_planet False --seed 3;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,1,2,3,4,5,6,7]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,1,2,3,4,5,6,7]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,1,2,3,4,5,6,7]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,1,2,3,4,5,6,7]  --use_testing True --resize_planet False --seed 3;

python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,1,2,3,4,5,6]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,1,2,3,4,5,6]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,1,2,3,4,5,6]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,1,2,3,4,5,6]  --use_testing True --resize_planet False --seed 3;

python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0]  --use_testing True --resize_planet False --seed 3;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [7]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [7]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [7]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [7]  --use_testing True --resize_planet False --seed 3;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,7]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,7]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,7]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 True --use_planet False --use_s1 False --use_s2 False --batch_size 4 --l8_bands [0,7]  --use_testing True --resize_planet False --seed 3;

#S2
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,0]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,0]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,0]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,0]  --use_testing True --resize_planet False --seed 3;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,0,6]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,0,6]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,0,6]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,0,6]  --use_testing True --resize_planet False --seed 3;



python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,6]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,6]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,6]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,6]  --use_testing True --resize_planet False --seed 3;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,0,6]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,0,6]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,0,6]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,0,6]  --use_testing True --resize_planet False --seed 3;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,6]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,6]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,6]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,6]  --use_testing True --resize_planet False --seed 3;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [1,6]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [1,6]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [1,6]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [1,6]  --use_testing True --resize_planet False --seed 3;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,6]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,6]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,6]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [2,1,6]  --use_testing True --resize_planet False --seed 3;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [0,1,2,3,4,5,6,7,8,9]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [0,1,2,3,4,5,6,7,8,9]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [0,1,2,3,4,5,6,7,8,9]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [0,1,2,3,4,5,6,7,8,9]  --use_testing True --resize_planet False --seed 3;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [3]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [3]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [3]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [3]  --use_testing True --resize_planet False --seed 3;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [4]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [4]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [4]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [4]  --use_testing True --resize_planet False --seed 3;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [5]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [5]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [5]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [5]  --use_testing True --resize_planet False --seed 3;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [7]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [7]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [7]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [7]  --use_testing True --resize_planet False --seed 3;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [3,4,5,7]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [3,4,5,7]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [3,4,5,7]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 False --use_s2 True --batch_size 4 --s2_bands [3,4,5,7]  --use_testing True --resize_planet False --seed 3;


python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0,1,2]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0,1,2]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0,1,2]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0,1,2]  --use_testing True --resize_planet False --seed 3;

python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [2]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [2]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [2]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [2]  --use_testing True --resize_planet False --seed 3;

python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0]  --use_testing True --resize_planet False --seed 3;

python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [1]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [1]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [1]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [1]  --use_testing True --resize_planet False --seed 3;

python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0,2]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0,2]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0,2]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [0,2]  --use_testing True --resize_planet False --seed 3;

python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [1,2]  --use_testing True --resize_planet False --seed 0;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [1,2]  --use_testing True --resize_planet False --seed 1;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [1,2]  --use_testing True --resize_planet False --seed 2;
python train_crop_yield.py --path_to_cauvery ../../cauvery --model_name unet-fc-yield --num_timesteps 184 --include_indices True --use_l8 False --use_planet False --use_s1 True --use_s2 False --batch_size 4 --s1_bands [1,2]  --use_testing True --resize_planet False --seed 3;
